# Generated by Django 3.0.6 on 2020-05-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='status',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attachment',
            name='url',
            field=models.CharField(default=1, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='', verbose_name='file'),
        ),
    ]
