# Generated by Django 3.0.6 on 2020-05-28 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0004_auto_20200528_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Failed'), (1, 'Pending'), (2, 'Done')], default=1),
        ),
    ]
